# Dockerfile
FROM python:3.12

# Set the working directory in the container
WORKDIR /myapp

# Copy all the files from your local directory to the container
COPY . .

# Run the sum.py script
CMD ["python", "sum.py"]
